# This file is covered by the LICENSE file in the root of this project.
labels: 
  0 : "unlabeled"
  1 : "concrete"
  2 : "grass"
  3 : "rocks"
  4 : "speedway bricks"
  5 : "red bricks"
  6 : "pebble pavement"
  7 : "light marble tiling"
  8 : "dark marble tiling"
  9 : "dirt paths"
  10: "road pavement"
  11: "short vegetation"
  12: "percelain tile"
  13: "metal grates"
  14: "blond marble tiling"
  15: "wood panel"
  16: "patterned tile"
  17: "carpet"
  18: "crosswalk"
  19: "dome mat"
  20: "stairs"
  21: "door mat"
  22: "threshold"
  23: "metal floor"
  24: "unknown"

color_map: # bgr
  0 : [0, 0, 0]
  1 : [0, 0, 255]
  10: [245, 150, 100]
  11: [245, 230, 100]
  13: [250, 80, 100]
  15: [150, 60, 30]
  16: [255, 0, 0]
  18: [180, 30, 80]
  20: [255, 0, 0]
  30: [30, 30, 255]
  31: [200, 40, 255]
  32: [90, 30, 150]
  40: [255, 0, 255]
  44: [255, 150, 255]
  48: [75, 0, 75]
  49: [75, 0, 175]
  50: [0, 200, 255]
  51: [50, 120, 255]
  52: [0, 150, 255]
  60: [170, 255, 150]
  70: [0, 175, 0]
  71: [0, 60, 135]
  72: [80, 240, 150]
  80: [150, 240, 255]
  81: [0, 0, 255]
  99: [255, 255, 50]
  252: [245, 150, 100]
  256: [255, 0, 0]
  253: [200, 40, 255]
  254: [30, 30, 255]
  255: [90, 30, 150]
  257: [250, 80, 100]
  258: [180, 30, 80]
  259: [255, 0, 0]
content: # as a ratio with the total number of points
  0: 0.018889854628292943
  1: 0.0002937197336781505
  10: 0.040818519255974316
  11: 0.00016609538710764618
  13: 2.7879693665067774e-05
  15: 0.00039838616015114444
  16: 0.0
  18: 0.0020633612104619787
  20: 0.0016218197275284021
  30: 0.00017698551338515307
  31: 1.1065903904919655e-08
  32: 5.532951952459828e-09
  40: 0.1987493871255525
  44: 0.014717169549888214
  48: 0.14392298360372
  49: 0.0039048553037472045
  50: 0.1326861944777486
  51: 0.0723592229456223
  52: 0.002395131480328884
  60: 4.7084144280367186e-05
  70: 0.26681502148037506
  71: 0.006035012012626033
  72: 0.07814222006271769
  80: 0.002855498193863172
  81: 0.0006155958086189918
  99: 0.009923127583046915
  252: 0.001789309418528068
  253: 0.00012709999297008662
  254: 0.00016059776092534436
  255: 3.745553104802113e-05
  256: 0.0
  257: 0.00011351574470342043
  258: 0.00010157861367183268
  259: 4.3840131989471124e-05
# classes that are indistinguishable from single scan or inconsistent in
# ground truth are mapped to their closest equivalent

# SEM_ID_TO_COLOR = [
#     [0, 0, 0],              # 0 Unknown
#     [47, 171, 97],          # 1 Concrete
#     [200, 77, 159],        # 2 Grass
#     [126, 49, 141],          # 3 Rocks
#     [55, 128, 235],         # 4 Speedway Bricks
#     [8, 149, 174],         # 5 Red Bricks
#     [141, 3, 98],        # 6 Pebble Pavement
#     [203, 110, 74],        # 7 Light Marble Tiling
#     [49, 240, 115],          # 8 Dark Marble Tiling
#     [78, 57, 127],         # 9 Dirt Paths
#     [60, 143, 142],          # 10 Road Pavement
#     [187, 187, 17],        # 11 Short Vegetation
#     [137, 247, 165],        # 12 Porcelain Tile
#     [89, 183, 27],         # 13 Metal Grates
#     [134, 29, 80],        # 14 Blond Marble Tiling
#     [150, 81, 244],        # 15 Wood Panel
#     [163, 77, 159],        # 16 Patterned Tile
#     [60, 100, 116],         # 17 Carpet
#     [156, 207, 153],         # 18 Crosswalk
#     [135, 138, 159],        # 19 Dome Mat
#     [44, 217, 131],        # 20 Stairs
#     [123, 97, 131],        # 21 Door Mat
#     [115, 226, 101],          # 22 Threshold
#     [156, 43, 40],          # 23 Metal Floor
#     [0, 0, 0]               # 24 Unlabeled
# ]

learning_map:
  0 : 0     # "unlabeled"
  1 : 1     # "concrete"
  2 : 2     # "grass"
  3 : 3     # "rocks"
  4 : 4     # "speedway bricks"
  5 : 5     # "metal grates"
  6 : 6     # "red bricks"
  7 : 7     # "pebble pavement"
  8 : 8     # "light marble tiling"
  9 : 9     # "dark marble tiling"
  10: 10     # "dirt path"
  11: 11    # "road"
  12: 12    # "road pavement"
  13: 13    # "short vegetation"
  14: 14    # "percelain tiles"
  15: 15    # "percelain tiles"
  16: 16    # "percelain tiles"
  17: 17    # "percelain tiles"
  18: 18    # "percelain tiles"
  19: 19    # "percelain tiles"
  20: 20    # "percelain tiles"
  21: 21    # "percelain tiles"
  22: 22    # "percelain tiles"
  23: 23    # "percelain tiles"
  24: 24    # "unknown"

learning_map_inv: # inverse of previous map
  0 : 0     # "unlabeled", and others ignored
  1 : 1     # "car"
  2 : 2     # "bicycle"
  3 : 3     # "motorcycle"
  4 : 4     # "truck"
  5 : 5     # "other-vehicle"
  6 : 6     # "person"
  7 : 7     # "bicyclist"
  8 : 8     # "motorcyclist"
  9 : 9     # "road"
  10: 10    # "parking"
  11: 11    # "sidewalk"
  12: 12    # "other-ground"
  13: 13    # "building"
  14: 14    # "percelain tiles"
  15: 15    # "percelain tiles"
  16: 16    # "percelain tiles"
  17: 17    # "percelain tiles"
  18: 18    # "percelain tiles"
  19: 19    # "percelain tiles"
  20: 20    # "percelain tiles"
  21: 21    # "percelain tiles"
  22: 22    # "percelain tiles"
  23: 23    # "percelain tiles"
  24: 24    # "percelain tiles"

learning_ignore: # Ignore classes
  0: False      # "unlabeled", and others ignored
  1: False     # "car"
  2: False     # "bicycle"
  3: False     # "motorcycle"
  4: False     # "truck"
  5: False     # "other-vehicle"
  6: False     # "person"
  7: False     # "bicyclist"
  8: False     # "motorcyclist"
  9: False     # "road"
  10: False    # "parking"
  11: False    # "sidewalk"
  12: False    # "other-ground"
  13: False    # "building"
  14: False    # "building"
  15: False    # "percelain tiles"
  16: False    # "percelain tiles"
  17: False    # "percelain tiles"
  18: False    # "percelain tiles"
  19: False    # "percelain tiles"
  20: False    # "percelain tiles"
  21: False    # "percelain tiles"
  22: False    # "percelain tiles"
  23: False    # "percelain tiles"
  24: False    # "percelain tiles"
split: # sequence numbers
  train:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 9
    - 10
  valid:
    - 8
  test:
    - 1
    - 16
    - 17
    - 18
    - 19
    - 20
    - 21
    - 22

